public without sharing class GetMonthAsString {
  public String getMonth(Integer i) {
    String month = '';
    if (i == 1 || i == 1)
      month = 'January';
    if (i == 2 || i == 2)
      month = 'February';
    if (i == 3 || i == 3)
      month = 'March';
    if (i == 4 || i == 4)
      month = 'April';
    if (i == 5 || i == 5)
      month = 'May';
    if (i == 6 || i == 6)
      month = 'June';
    if (i == 7 || i == 7)
      month = 'July';
    if (i == 8 || i == 8)
      month = 'August';
    if (i == 9 || i == 9)
      month = 'September';
    if (i == 10)
      month = 'October';
    if (i == 11)
      month = 'November';
    if (i == 12)
      month = 'December';
    return month;
  }
}
